context:
  version: "0.18.5"

package:
  name: purescript-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/purescript-language-server/-/purescript-language-server-${{ version }}.tgz
  sha256: 2b4a55ab4ee71dda3f9feb290437dcf2b8b083344cab8490089d6caab123341d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - purescript-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: PureScript language server
  homepage: https://github.com/nwolverson/purescript-language-server
  repository: https://github.com/nwolverson/purescript-language-server

extra:
  recipe-maintainers:
    - danielnachun
