context:
  version: 0.18.0

package:
  name: purescript-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/purescript-language-server/-/purescript-language-server-${{ version }}.tgz
  sha256: 4814f287375c5b03ff71d11ab43e2eab7c87bb4d856d22db70cd45f9051ec327

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - purescript-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: PureScript language server
  homepage: https://github.com/nwolverson/purescript-language-server
  repository: https://github.com/nwolverson/purescript-language-server

extra:
  recipe-maintainers:
    - danielnachun
